events = [
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "put", "Type": "transition_event"}, "Type": {"Head": "transition", "Args": {"Arg": [{"@Name": "A1", "@Value": "x:agent"}, {"@Name": "A2", "@Value": "y:physobj"}, {"@Name": "A3", "@Value": "z:location"}]},"Body": {"Subevents": [{"@Name": "E1", "@Value": "grasp(x,y)"}, {"@Name": "E2", "@Value": "[while(hold(x,y),move(x)]"}, {"@Name": "E1", "@Value": "[at(y,z)->ungrasp(x,y)]"}]}}},'event':'put'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "slide", "Type": "process"}, "Type": {"Head": "transition", "Args": {"Arg": [{"@Name": "A1", "@Value": "x:physobj"}, {"@Name": "A2", "@Value": "y:physobj"}]},"Body": {"Subevents": [{"@Name": "E1", "@Value": "while(EC(x,y),move(x))"}]}}},'event':'slide'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "grasp", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'grasp'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "hold", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'hold'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "touch", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'touch'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "move", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'move translocate'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "move", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'move rotate'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "roll", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'roll'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "spin", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'spin'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "stack", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'stack'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "lean", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'lean (on/against)'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "flip", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'pivoted object rotation (flip on edge)'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "flip", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'flip at center'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "close", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'close'},
	{"VoxML": {"@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "@xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "Lex": {"Pred": "open", "Type": ""}, "Type": {"Head": "", "Args": null,"Body": null}},'event':'open'}
]