events = [
	{'event':'grasp'},
	{'event':'hold'},
	{'event':'touch'},
	{'event':'move translocate'},
	{'event':'move rotate'},
	{'event':'roll'},
	{'event':'spin'},
	{'event':'stack'},
	{'event':'put'},
	{'event':'lean (on/against)'},
	{'event':'pivoted object rotation (flip on edge)'},
	{'event':'flip at center'},
	{'event':'close'},
	{'event':'open'},
	{'event':'touching'},
	{'event':'in'},
	{'event':'on'},
	{'event':'behind'},
	{'event':'in front of'},
	{'event':'near'},
	{'event':'left of'},
	{'event':'right of'}
]